# Generated by Django 2.0 on 2018-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='friend_id',
            field=models.IntegerField(default=1, verbose_name='聊天朋友'),
            preserve_default=False,
        ),
    ]
