# Generated by Django 2.0 on 2018-12-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0003_chatmessage_friend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='自己'),
            preserve_default=False,
        ),
    ]
