# Generated by Django 2.0 on 2018-12-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0004_auto_20181229_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='is_read',
            new_name='is_write',
        ),
    ]
