# Generated by Django 2.0 on 2018-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0005_auto_20181229_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_write',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='write_id',
            field=models.IntegerField(default=1, verbose_name='发送消息者'),
            preserve_default=False,
        ),
    ]
