# Generated by Django 2.0 on 2019-01-08 02:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0006_auto_20181231_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='message',
            field=tinymce.models.HTMLField(verbose_name='消息'),
        ),
    ]
