# Generated by Django 2.0 on 2019-01-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0007_auto_20190108_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='message',
            field=models.TextField(verbose_name='消息'),
        ),
    ]
