# Generated by Django 2.0 on 2019-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0011_auto_20190108_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='heads',
            field=models.CharField(default=1, max_length=200, verbose_name='消息头'),
            preserve_default=False,
        ),
    ]
